#!/usr/bin/env python

# Purpose: summarize coverage data from hmcnc output (hmm/cov_bins.bed) used in GetCoverageOfRegions.sh
# Input: "\n"-separated list of coverage data points 
# Output: <coverage> <median bin coverage> <std dev of bin coverage> <variance of bin coverage> <num bins>

import sys
import math
import numpy as np
vals=[]
for line in sys.stdin:
    vals.append(float(line.strip()))
s=sorted(vals)
n=int(len(s)/2)
sys.stdout.write(str(sum(vals)/len(vals) ) + "\t" + str(s[n])+ "\t{:4.4f}\t{:4.4f}\t".format(np.std(vals), np.var(vals)) + str(len(s)) + "\n")