#!/usr/bin/env python
import sys
import math
import numpy as np
vals=[]
for line in sys.stdin:
    vals.append(float(line.strip()))
s=sorted(vals)
n=int(len(s)/2)
sys.stdout.write(str(sum(vals)/len(vals) ) + "\t" + str(s[n])+ "\t{:4.4f}\t{:4.4f}\t".format(np.std(vals), np.var(vals)) + str(len(s)) + "\n")
